app/BenchesAlmaty/urls.py
from django.urls import include, path
from django.views.generic.base import RedirectView
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from userSystem import views as user_views
from benches import views as benches_views

app_name = 'mySite'

urlpatterns = [
    path('favicon.ico/', RedirectView.as_view(url='/static/img/reread-logo.ico', permanent=True), name='favicon'),
    path('admin/', admin.site.urls),
    path('rosetta/', include('rosetta.urls')),
    path('', include('mySite.urls')),
    path('i18n/', include('django.conf.urls.i18n')),

    # login system
    path('register/', user_views.register, name='register'),
    path('login/', user_views.user_login, name='login'),
    path('logout/', user_views.user_logout, name='logout'),

    # profile system
    path('profile/', user_views.view_profile, name='view_profile'),
    path('profile/edit/', user_views.edit_profile, name='edit_profile'),

    path('profile/<str:username>/', user_views.other_user_profile, name='other_user_profile'),

    # bench system
    path('benches/', include('benches.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/benches/urls.py
from django.urls import path
from . import views

app_name = 'benches'

urlpatterns = [
    path('create_bench/', views.create_bench, name='create_bench'),
    path('', views.bench_list, name='bench_list'),
    path('bench/<int:bench_id>/', views.bench_detail, name='bench_detail'),
]

app/benches_almaty/urls.py
from django.urls import include, path
from django.views.generic.base import RedirectView
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from userSystem import views as user_views

urlpatterns = [
    path('favicon.ico/', RedirectView.as_view(url='/static/img/reread-logo.ico', permanent=True), name='favicon'),
    path('admin/', admin.site.urls),
    path('rosetta/', include('rosetta.urls')),
    path('', include('mySite.urls', namespace='mySite')),  # Добавлен namespace
    path('i18n/', include('django.conf.urls.i18n')),

    # login system
    path('register/', user_views.register, name='register'),
    path('login/', user_views.user_login, name='login'),
    path('logout/', user_views.user_logout, name='logout'),

    # profile system
    path('profile/', user_views.view_profile, name='view_profile'),
    path('profile/edit/', user_views.edit_profile, name='edit_profile'),
    path('profile/<str:username>/', user_views.other_user_profile, name='other_user_profile'),

    # bench system
    path('benches/', include('benches.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/mySite/urls.py
from django.urls import path
from . import views

app_name = 'mySite'

urlpatterns = [
    path('map/', views.index, name='index'),
    path('', views.about, name='about'),
]

app/mySite/views.py
from django.shortcuts import render

from benches.models import Bench
from userSystem.models import Profile


def index(request):
    benches = Bench.objects.all()

    if request.user.is_authenticated:
        # TODO: исправить костыль с отображением фото, сделать проверку в шаблоне
        profile, created = Profile.objects.get_or_create(user=request.user)
        context = {'profile': profile, 'benches': benches}
    else:
        context = {'benches': benches}

    return render(request, "mySite/index.html", context)

def about(request):
    return render(request, "mySite/about.html")

app/mySite/templates/mySite/about.html
{% extends "mySite/base.html" %}
{% load static tailwind_tags i18n %}

{% block title %}{% trans "О проекте" %}{% endblock %}

{% block content %}
<body class="bg-green-50 leading-normal tracking-normal">
    <section class="relative w-full bg-gradient-to-r from-green-500 to-yellow-400 py-20 px-6 text-white">
        <div class="container mx-auto text-center">
            <h1 class="text-4xl md:text-5xl font-bold mb-4">{% trans "Карта скамеек Алматы" %}</h1>
            <p class="text-lg md:text-xl max-w-2xl mx-auto">
                {% trans "Наш проект помогает жителям и гостям Алматы находить удобные места для отдыха. Мы собираем данные о расположении скамеек, условиях окружающей среды и удобствах поблизости." %}
            </p>
        </div>
    </section>

    <section class="container mx-auto my-10 px-6">
        <h2 class="text-3xl font-semibold text-center mb-6 text-green-800">{% trans "Почему это важно?" %}</h2>
        <div class="grid md:grid-cols-3 gap-6">
            <div class="bg-white shadow-lg rounded-lg p-6 text-center">
                <img src="https://img.icons8.com/ios-filled/100/4caf50/city.png" alt="Community" class="mx-auto h-16 mb-4">
                <h3 class="text-xl font-semibold mb-2">{% trans "Городская среда" %}</h3>
                <p class="text-gray-600">{% trans "Мы помогаем делать город удобнее, показывая места для отдыха и общения." %}</p>
            </div>
            <div class="bg-white shadow-lg rounded-lg p-6 text-center">
                <img src="https://img.icons8.com/?size=100&id=955&format=png&color=4caf50" alt="Health" class="mx-auto h-16 mb-4">
                <h3 class="text-xl font-semibold mb-2">{% trans "Здоровье и комфорт" %}</h3>
                <p class="text-gray-600">{% trans "Скамейки важны для пожилых людей, родителей с детьми и всех, кто хочет передохнуть." %}</p>
            </div>
            <div class="bg-white shadow-lg rounded-lg p-6 text-center">
                <img src="https://img.icons8.com/?size=100&id=826&format=png&color=4caf50" alt="Nature" class="mx-auto h-16 mb-4">
                <h3 class="text-xl font-semibold mb-2">{% trans "Экология и отдых" %}</h3>
                <p class="text-gray-600">{% trans "Скамейки часто находятся в парках, создавая точки для наслаждения природой." %}</p>
            </div>
        </div>
    </section>

    <section class="container mx-auto px-6 my-10">
        <div class="flex justify-center">
            <div id="map" class="w-full max-w-screen-lg h-96 rounded-lg shadow-lg"></div>
        </div>

        <script src="https://maps.api.2gis.ru/2.0/loader.js?pkg=full&skin=dark"></script>
        <script type="text/javascript">
		
            var map;
        
            DG.then(function() {
                        // загрузка кода модуля
                        return DG.plugin('https://unpkg.com/leaflet.markercluster@1.4.1/dist/leaflet.markercluster.js');
                    }).then(function() {
                
                map = DG.map('map', {
                    center: [43.241025, 76.957485],
                    zoom: 15
                });
    
                    console.log('Страница загружена!');
    
                        if (localStorage.getItem('isShow') == 1){
                            localStorage.setItem('isShow', 0);
                            var show_location_latitude = localStorage.getItem('benchLat');
                            var show_location_longitude = localStorage.getItem('benchLon');
                            
                            console.log(show_location_latitude.replace(',', '.'));
                            console.log(show_location_longitude);
    
                            map.setView([show_location_latitude.replace(',', '.'), show_location_longitude.replace(',', '.')]);
                            
                        }
                        
                DG.control.location({position: 'bottomright'}).addTo(map);
                // DG.control.scale().addTo(map);
                // DG.control.ruler({position: 'bottomleft'}).addTo(map);
                // DG.control.traffic().addTo(map);
        
                your_locationIcon = DG.icon({
                            iconUrl: '{% static "img/your_location.png" %}',
                            iconSize: [24, 24]
                });
        
                catec_collegeIcon = DG.icon({
                            iconUrl: '{% static "img/catecCollege.png" %}',
                            iconSize: [48, 24]
                });
    
                benchIcon = DG.icon({
                    iconUrl: '{% static "img/bench.png" %}',
                    iconSize: [24, 24]
                });
    
                var markers = DG.markerClusterGroup();
    
                {% for bench in benches %}
                    var popup = `
                    <div id="bench-{{ bench.id }}" class="w-28 h-60">
                        <a href="" class="flex items-center underline">
                            <p class="text-sm text-white">Скамейка &nbsp;<p class="text-lg text-white">{{ bench.id }}</p></p>
                        </a>
                        <p>
                            Спинка:&nbsp;&nbsp;
                            {% if bench.has_backrest %}
                                ✅
                            {% elif bench.has_backrest %}
                                ❌
                            {% else %}
                                ❔
                            {% endif %}
                        </p> 
                        <p>
                            Урна:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                            {% if bench.has_bin %}
                                ✅
                            {% elif bench.has_bin %}
                                ❌
                            {% else %}
                                ❔
                            {% endif %}
                        </p> 
    
                        <br/>
                        <p>{{ bench.type.name }}</p>
                        <p>{{ bench.district.name }}</p>
                        <p>{{ bench.environment.name }}</p>
    
                        <p>
                            {% if bench.rating == 0 %}
                            Нет оценок
                            <br/>
                            {% else %}
                                {% for i in "0123456789"|slice:bench.get_rating %}
                                    ⭐
                                {% endfor %}</p>
                            {% endif %}
                            <br/>
    
                        <a href="">
                            <img class="w-28 h-16" src="{{ bench.get_avatar_url }}" alt="Фото скамейки">
                        </a>
                        
                        <br/>
                    </div>`;
    
                    var marker = DG.marker(['{{ bench.location_latitude }}'.replace(',', '.'), '{{ bench.location_longitude }}'.replace(',', '.')], {
                        icon: benchIcon
                    })
                    .addTo(map)
                    .bindPopup(popup);
    
                    markers.addLayer(marker);
    
                {% endfor %}
    
                DG.marker([43.241025, 76.957485], {
                    icon: catec_collegeIcon
                }).addTo(map).bindPopup('Центральноазиатский технико-экономический колледж');
        
                map.locate({ watch: true})
                            .on('locationfound', function(e) {
        
        
                                DG.marker([e.latitude, e.longitude], {
                                    icon: your_locationIcon
                                })
                                .addTo(map)
                                .bindLabel('Ваше местоположение!')
                                .bindPopup(
                                    '<p>Вы находитесь здесь.');
                            })
                            .on('locationerror', function(e) {
                                DG.popup()
                                  .setLatLng(map.getCenter())
                                  .setContent('Доступ к определению местоположения отключён')
                                  .openOn(map);
                            });
    
                
                
                
                
    
                map.addLayer(markers);
    
    
            });
        </script>
    </section>

    <section class="container mx-auto my-10 px-6 text-center">
        <h2 class="text-3xl font-semibold text-green-800">{% trans "Присоединяйтесь к нам!" %}</h2>
        <p class="text-gray-600 mt-4 max-w-xl mx-auto">
            {% trans "Если вы хотите добавить информацию о новых скамейках или поддержать проект, напишите нам!" %}
        </p>
        
        <div class="flex flex-col md:flex-row justify-center gap-4 mt-6">
            <a href="{% url 'mySite:index' %}" class="inline-block bg-green-600 hover:bg-green-700 text-white font-semibold py-3 px-6 rounded-lg transition duration-300">
                {% trans "Открыть полную версию" %}
            </a>
            <a href="/login" class="inline-block bg-blue-500 hover:bg-blue-600 text-white font-semibold py-3 px-6 rounded-lg transition duration-300">
                {% trans "Войти, чтобы добавлять скамейки" %}
            </a>
        </div>
    </section>
    
</body>
{% endblock content %}

app/mySite/templates/mySite/base.html
{% load static tailwind_tags i18n %}
{% get_current_language as language_code %}


<!DOCTYPE html>
<html lang="{{ language_code }}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% tailwind_css %}
    <link rel="stylesheet" src="{% static 'styles.css' %}">
    <title>
        {% block title %}{% endblock %} — {% trans 'Карта скамеек Алматы' %}
    </title>
    <script src="https://cdn.tailwindcss.com"></script>

</head>
<body class="font-sans">
    <div class="header">
        {% include 'mySite/header.html' %}
    </div>
    <div class="main xl:ml-15 md:ml-10 ml-5">
        {% block content %}{% endblock %}
    </div>
    

</body>
</html>

app/mySite/templates/mySite/header.html
{% load static %}
{% load static tailwind_tags %}
{% load i18n %}
{% get_current_language as language_code %}

<script src="https://cdn.jsdelivr.net/npm/alpinejs@2.8.2/dist/alpine.min.js" defer></script>

<header class="leading-normal tracking-normal z-999 flex justify-between">

    <nav class="bg-yellow-50 flex items-center justify-between flex-wrap bg-grey-darkest w-full z-10 px-6 py-3">
        <div class="flex items-center flex-no-shrink text-white mr-6">
            <a class="text-black no-underline hover:text-green-500 hover:no-underline flex items-center flex-no-shrink" href="{% url 'mySite:index' %}">
            <img class="h-16" src="{% static 'img/benchIcon.png' %}" alt="Bench Icon"/>
              <span class="text-2xl pl-2"><i class="em em-grinning"></i>{% trans 'Карта скамеек Алматы' %}</span>
            </a>
          </div>
          
        <div>
          <a href="{% url 'mySite:about' %}" class="inline-block text-lg text-grey-dark no-underline hover:text-green-500 hover:text-underline">{% trans 'О проекте' %}</a>
                  
        </div>

        <div class="block lg:hidden">
            <button id="nav-toggle" class="flex items-center px-3 py-2 border rounded text-grey border-grey-dark hover:text-white hover:border-white">
                <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
            </button>
        </div>

        <div class="w-full flex-grow lg:items-center lg:w-auto hidden lg:block pt-6 lg:pt-0 " id="nav-content">

            <ul class="list-reset lg:flex justify-end flex-1 items-center text-xl">
              <form id="language-form" action="{% url 'set_language' %}" method="post" class="">
                {% csrf_token %}
                <select name="language" onchange="this.form.submit()" class="appearance-auto bg-none rounded-xl text-base px-2 py-1 inline-flex focus:ring-0 focus:outline-none focus:ring-transparent mr-4">
                    {% get_available_languages as LANGUAGES %}
                    {% get_language_info_list for LANGUAGES as languages %}
                    {% for language in languages %}
                        <option value="{{ language.code }}" {% if language.code == LANGUAGE_CODE %}selected{% endif %} class="justify-center">
                            {{ language.name_local }}
                        </option>
                    {% endfor %}
                </select>
            </form>

                <li class="mr-3">
                    <a class="hover:text-green-500" href="{% url 'benches:bench_list' %}">{% trans 'Список скамеек' %}</a>
                </li>
                <li class="mr-3">
                  {% if user.is_authenticated %}
                    <a href="{% url 'benches:create_bench' %}" class="inline-block text-grey-dark no-underline hover:text-green-500 hover:text-underline py-2 lg:px-4">{% trans 'Создать скамейку' %}</a>
                  {% else %}

                  {% endif %}
                    
                </li>
                
            </ul>
        </div>

                <div class="">
                    <div x-data="{ open: false }" class="relative inline-block text-left">
                      <button @click="open = !open" class="inline-flex justify-center w-full px-4 py-2 font-medium text-gray-700 bg-white border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-offset-gray-100 focus:ring-blue-500">
                        {% trans 'Профиль' %}

                        {% if user.is_authenticated %}
                        <img class="h-7 w-7 ml-2 rounded-xl"
                        src="{{ profile.get_avatar_url|default:'/media/default.png' }}" 
                        alt="avatar">
                   
                        {% else %}

                        {% endif %}

                        <svg class="h-5 w-5 ml-2" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"></path>
                        </svg>
                      </button>
                      <div x-show="open" @click.away="open = false" class="origin-top-left absolute left-0 mt-2 w-56 rounded-md shadow-lg bg-white ring-1 ring-black ring-opacity-5 px-2 py-2">
                        {% if user.is_authenticated %}
                            <a href="{% url 'view_profile' %}" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 rounded-md">{% trans 'Профиль' %}</a>
                                                        
                            <a href="{% url 'edit_profile' %}" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 rounded-md">{% trans 'Настройки' %}</a>

                            <a href="{% url 'logout' %}" class="block px-4 py-2 text-sm text-red-500 hover:bg-red-100 rounded-md">{% trans 'Выйти' %}</a>
                        {% else %}
                            <a href="{% url 'login' %}" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 rounded-md">{% trans 'Войти' %}</a>
                            <a href="{% url 'register' %}" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 rounded-md">{% trans 'Зарегистрироваться' %}</a>
                        {% endif %}
                        <p class="block px-4 border-b-2"></p>
                        <a href="{% url 'mySite:about' %}" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 rounded-md">{% trans 'О проекте' %}</a>
                        
                      </div>
                    </div>
                </div>
                

        <script>
        function selected() {
            var targeted = event.target;
            var clicked = targeted.parentElement;
          
            var child = clicked.children;
            console.log(child);
          
            for (let i = 0; i < child.length; i++) {
              if (child[i].classList.contains("text-white")) {
                console.log(child[i]);
                child[i].classList.remove("text-white", "bg-indigo-600");
                child[i].classList.add(
                  "text-gray-600",
                  "bg-gray-50",
                  "border",
                  "border-white"
                );
              }
            }
          
            targeted.classList.remove(
              "text-gray-600",
              "bg-gray-50",
              "border",
              "border-white"
            );
            targeted.classList.add("text-white", "bg-indigo-600");
          }
        </script>

    </nav>

    <!--Container-->


    <script>
        //Javascript to toggle the menu
        document.getElementById('nav-toggle').onclick = function(){
            document.getElementById("nav-content").classList.toggle("hidden");
        }
    </script>

</header>

app/mySite/templates/mySite/index.html
{% extends "mySite/base.html" %}
{% load static tailwind_tags i18n %}

{% block title %}Главная{% endblock %}

{% block content %}
<body class="bg-gray-50 leading-normal tracking-normal">
	<script src="https://maps.api.2gis.ru/2.0/loader.js?pkg=full&skin=dark"></script>
    
    <link rel="stylesheet" href="https://unpkg.com/leaflet.markercluster@1.4.1/dist/MarkerCluster.css" />
    <link rel="stylesheet" href="https://unpkg.com/leaflet.markercluster@1.4.1/dist/MarkerCluster.Default.css" />
	<script src="https://maps.api.2gis.ru/2.0/cluster_realworld.js"></script>

	<div class="container width: 100vw; -ml-10">

		<div id="map" style="margin-left: 0px; width: 100vw;; height:86.5vh"></div>
		
	</div>

	<script type="text/javascript">
		
		var map;
	
		DG.then(function() {
					// загрузка кода модуля
					return DG.plugin('https://unpkg.com/leaflet.markercluster@1.4.1/dist/leaflet.markercluster.js');
				}).then(function() {
			
				var urlParams = new URLSearchParams(window.location.search);
				var lat = urlParams.get("lat");
				var lon = urlParams.get("lon");


				if (lat && lon) {
					lat = lat.replace(",", ".");  // Меняем запятую на точку
					lon = lon.replace(",", ".");  // Меняем запятую на точку
					lat = parseFloat(lat);
					lon = parseFloat(lon);

					if (!isNaN(lat) && !isNaN(lon)) {
						map = DG.map('map', {
						center: [lat, lon],
						zoom: 20
					});
					}
				}
				else(
					map = DG.map('map', {
						center: [43.241025, 76.957485],
						zoom: 15
					})
				)
			DG.control.location({position: 'bottomright'}).addTo(map);
			DG.control.scale().addTo(map);
			DG.control.ruler({position: 'bottomleft'}).addTo(map);
			DG.control.traffic().addTo(map);
	
			your_locationIcon = DG.icon({
						iconUrl: '{% static "img/your_location.png" %}',
						iconSize: [24, 24]
			});
	
			catec_collegeIcon = DG.icon({
						iconUrl: '{% static "img/catecCollege.png" %}',
						iconSize: [48, 24]
			});

			benchIcon = DG.icon({
				iconUrl: '{% static "img/bench.png" %}',
				iconSize: [24, 24]
			});

			var markers = DG.markerClusterGroup();

			{% for bench in benches %}
				var popup = `
				<div id="bench-{{ bench.id }}" class="w-28 h-60">
					<a href="" class="flex items-center underline">
						<p class="text-sm text-white">Скамейка &nbsp;<p class="text-lg text-white">{{ bench.id }}</p></p>
					</a>
					<p>
						Спинка:&nbsp;&nbsp;
						{% if bench.has_backrest %}
							✅
						{% elif bench.has_backrest %}
							❌
						{% else %}
							❔
						{% endif %}
					</p> 
					<p>
						Урна:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
						{% if bench.has_bin %}
							✅
						{% elif bench.has_bin %}
							❌
						{% else %}
							❔
						{% endif %}
					</p> 

					<br/>
					<p>{{ bench.type.name }}</p>
					<p>{{ bench.district.name }}</p>
					<p>{{ bench.environment.name }}</p>

					<p>
						{% if bench.rating == 0 %}
						Нет оценок
						<br/>
						{% else %}
							{% for i in "0123456789"|slice:bench.get_rating %}
								⭐
							{% endfor %}</p>
						{% endif %}
						<br/>

					<a href="">
						<img class="w-28 h-16" src="{{ bench.get_avatar_url }}" alt="Фото скамейки">
					</a>
					
					<br/>
				</div>`;

				var marker = DG.marker(['{{ bench.location_latitude }}'.replace(',', '.'), '{{ bench.location_longitude }}'.replace(',', '.')], {
					icon: benchIcon
				})
				.addTo(map)
				.bindPopup(popup);

				markers.addLayer(marker);

			{% endfor %}

			DG.marker([43.241025, 76.957485], {
				icon: catec_collegeIcon
			}).addTo(map).bindPopup('Центральноазиатский технико-экономический колледж');
	
			map.locate({ watch: true})
						.on('locationfound', function(e) {
	
	
							DG.marker([e.latitude, e.longitude], {
								icon: your_locationIcon
							})
							.addTo(map)
							.bindLabel('Ваше местоположение!')
							.bindPopup(
								'<p>Вы находитесь здесь.');
						})
						.on('locationerror', function(e) {
							DG.popup()
							  .setLatLng(map.getCenter())
							  .setContent('Доступ к определению местоположения отключён')
							  .openOn(map);
						});

			
			
			
			

			map.addLayer(markers);


		});

		document.addEventListener("DOMContentLoaded", function () {
				var urlParams = new URLSearchParams(window.location.search);
				var lat = urlParams.get("lat");
				var lon = urlParams.get("lon");

				if (lat && lon) {
					lat = parseFloat(lat);
					lon = parseFloat(lon);
					if (!isNaN(lat) && !isNaN(lon)) {
						map = DG.map('map', {
						center: [lat, lon],
						zoom: 15
					});
					}
				}
			});
	</script>



</body>


{% endblock content %}